server:
  port: ${port:8088}
spring:
  profiles:
    active: dev
  datasource:
    initialize: false
    separator: /*--SEPARATOR--*/
    schema: classpath:schema-${spring.datasource.platform}.sql
    druid:
      initialSize: 1
      minIdle: 1
      maxActive: 10
      maxWait: 10000
      maxOpenPreparedStatements: -1
      validationQuery: select 'x'
      validationQueryTimeout: 1
      connection-properties: config.decrypt=true;config.decrypt.key=${public-key}
      filter:
        config:
          enabled: true
        stat:
          enabled: true
          merge-sql: true
          log-slow-sql: true
        slf4j:
          enabled: true
          data-source-log-enabled: false
          connection-log-enabled: false
          result-set-log-enabled: true
          statement-log-enabled: false
        wall:
          enabled: true
          config:
            noneBaseStatementAllow: true
logback:
  log-home: logs
  app-name: mlgb-framework
mybatis:
  type-aliases-package: cn.mlgbteam.**.entity
  mapper-locations: classpath:mapper/**/*.xml
pagehelper:
  reasonable: true
  page-size-zero: true
  supportMethodsArguments: true
  autoRuntimeDialect: true
mapper:
  before: true
  identity: SELECT uuid();
  mappers:
    - tk.mybatis.mapper.common.Mapper
    - tk.mybatis.mapper.common.MySqlMapper

---
# 开发环境配置
spring:
  profiles: dev
  datasource:
    platform: mysql
    druid:
      url: jdbc:mysql://lujunfeng.cn:3306/mlgbframework?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
      username: mlgb
      password: IwMbXUllGNmP7KZ0jg81WXAL77wSzn1FiRNXucN9gfLFPEEGnIW8CVYNg+oR+zVBd99irA3RnwLYC0yzvC2jqQ==
public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKRhzjxE1lIRvZ8duMdcTFDvEPD0RYPMwTGwLMvSKtTgIOsL/BQPajqDZmsiFCwH6vINESknnxiU1wxpSMHkyoUCAwEAAQ==

---
# 测试环境配置
spring:
  profiles: test

---
# 生产环境配置
spring:
  profiles: prod
